// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzd9YfsOXmTyisJHnTjkykqNAfvbLhzbE',
    appId: '1:916023538629:web:caf4b2f2d05fb6eb6991ac',
    messagingSenderId: '916023538629',
    projectId: 'alepedidos-5ce4c',
    authDomain: 'alepedidos-5ce4c.firebaseapp.com',
    storageBucket: 'alepedidos-5ce4c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg2R1r-76GEL8DoY2ipMJWgSUsboDXVPk',
    appId: '1:916023538629:android:f405fef92b136b246991ac',
    messagingSenderId: '916023538629',
    projectId: 'alepedidos-5ce4c',
    storageBucket: 'alepedidos-5ce4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtvBbJ6M0IILjTiVMqsIvmmW10OUVwedE',
    appId: '1:916023538629:ios:2eb96625c7f65e076991ac',
    messagingSenderId: '916023538629',
    projectId: 'alepedidos-5ce4c',
    storageBucket: 'alepedidos-5ce4c.firebasestorage.app',
    iosBundleId: 'com.example.alepedidos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtvBbJ6M0IILjTiVMqsIvmmW10OUVwedE',
    appId: '1:916023538629:ios:2eb96625c7f65e076991ac',
    messagingSenderId: '916023538629',
    projectId: 'alepedidos-5ce4c',
    storageBucket: 'alepedidos-5ce4c.firebasestorage.app',
    iosBundleId: 'com.example.alepedidos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzd9YfsOXmTyisJHnTjkykqNAfvbLhzbE',
    appId: '1:916023538629:web:349cdca9cd47572d6991ac',
    messagingSenderId: '916023538629',
    projectId: 'alepedidos-5ce4c',
    authDomain: 'alepedidos-5ce4c.firebaseapp.com',
    storageBucket: 'alepedidos-5ce4c.firebasestorage.app',
  );
}
